POST http://localhost:3000/vote HTTP/1.1
content-type: application/json

{
    "userUUID": "1293123121155",
    "articleId": "312312312",
    "vote": 1
}

#####

get http://localhost:3000/vote/312312312 HTTP/1.1
content-type: application/json
