### Vote to a new user
POST http://localhost:3000/api/vote HTTP/1.1
content-type: application/json

{
    "articleId": "312312312",
    "vote": 1
}

### Vote to an existing user
POST http://localhost:3000/api/vote HTTP/1.1
content-type: application/json

{
    "userId": "66da07552fc0b015948ad07a",
    "articleId": "312312312",
    "vote": 1
}

##### Get articles votes
get http://localhost:3000/api/vote/312312312 HTTP/1.1
content-type: application/json

##### Get votes for the user
get http://localhost:3000/api/vote/66da07552fc0b015948ad07a/312312312 HTTP/1.1
content-type: application/json

##### Sync articles
get http://localhost:3000/api/article/sync-database HTTP/1.1
content-type: application/json