apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  init-mongo.sh: |
    #!/bin/bash
    until mongo --eval "print(\"waited for connection\")"
    do
      sleep 5
    done
    mongo <<EOF
    use ${MONGO_DBNAME}
    db.createUser({
      "user" : "${MONGO_USER}",
      "pwd" : "${MONGO_PASS}",
      "roles" : [{ "role" : "readWrite", "db" : "${MONGO_DBNAME}" }]
    })
    EOF
---
apiVersion: v1
kind: Pod
metadata:
  name: juniorfox-site
  labels:
    app: juniorofox-site

spec:
  automountServiceAccountToken: false
  restartPolicy: Always
  containers:
  #- image: localhost/juniorfox-site:develop
  - image: ghcr.io/cjuniorfox/juniorfox-site:latest
    name: site
    env:
    - name: MONGO_USER
      valueFrom:
        secretKeyRef:
          name: juniorfox-site-secrets
          key: mongoUser
    - name: MONGO_PASS
      valueFrom:
        secretKeyRef:
          name: juniorfox-site-secrets
          key: mongoPassword
    - name: MONGO_DBNAME
      valueFrom:
        secretKeyRef:
          name: juniorfox-site-secrets
          key: mongoDatabase
    - name: MONGO_HOST
      value: juniorfox-site-db
    - name: MONGO_PORT
      value: 27017
    ports:
    - containerPort: 3000
      hostPort: 3000
  
  - image: docker.io/library/mongo:4.4
    name: db
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: root
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: juniorfox-site-secrets
          key: mongoPassword
    - name: MONGO_USER
      valueFrom:
        secretKeyRef:
          name: juniorfox-site-secrets
          key: mongoUser
    - name: MONGO_PASS
      valueFrom:
        secretKeyRef:
          name: juniorfox-site-secrets
          key: mongoPassword
    - name: MONGO_DBNAME
      valueFrom:
        secretKeyRef:
          name: juniorfox-site-secrets
          key: mongoDatabase
    volumeMounts:
    - name: mongo-init-script
      mountPath: /docker-entrypoint-initdb.d/
    - name: juniorfox-site-db-pvc
      mountPath: /data/db
    - name: juniorfox-site-configdb-pvc
      mountPath: /data/configdb

  volumes:
  - name: mongo-init-script
    configMap:
      name: mongo-init-script
  - name: juniorfox-site-db-pvc
    persistentVolumeClaim:
      claimName: juniorfox-site-db
  - name: juniorfox-site-configdb-pvc
    persistentVolumeClaim:
      claimName: juniorfox-site-configdb
