name: Build and Push Image to GHCR

on:
    push:
        branches:
            - develop

jobs:
    build_push:
      name: Build and push image
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
        id-token: write

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
              app/Containerfile
          image: ${{ github.event.repository.name}}
          oci: true
          context: ./app

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push Image to GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          registry: "ghcr.io/${{ github.repository_owner }}"
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
    
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Setup Wireguard
        run: |
          sudo apt install wireguard
          echo "ip address ${{ secrets.WG_IP }}" 
          echo "${{ secrets.WG_PRIVATE }}" > privatekey
          sudo ip link add dev wg0 type wireguard
          sudo ip address add dev wg0 ${{ secrets.WG_IP}}
          echo "Configuring wireguard connection"
          sudo wg set wg0 private-key privatekey \
            peer ${{ secrets.WG_ENDPOINT_PUBKEY }} \
            allowed-ips ${{ secrets.WG_ALLOWED_IPS }} \
            endpoint ${{ secrets.WG_ENDPOINT }}
          ping -c 4 10.10.10.1