name: Build and Deploy

on:
  push:
    branches:
    - main
    - feature/gcp

jobs:
    build_push:
      name: Build and push image
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
        id-token: write

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
              app/Containerfile
          image: ${{ github.event.repository.name}}
          oci: true
          context: ./app

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push Image to GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          registry: "ghcr.io/${{ github.repository_owner }}"
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
    
    deploy:
      if: false
      name: Deploy Application
      runs-on: ubuntu-latest
      needs: build_push
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Wireguard
        run: |
          sudo apt install wireguard
          echo "${{ secrets.WG_PRIVATE }}" > privatekey
          sudo ip link add dev wg0 type wireguard
          sudo ip -4 address add ${{ secrets.WG_IP}} dev wg0 
          echo "Configuring wireguard connection"
          sudo wg set wg0 private-key privatekey \
            peer ${{ secrets.WG_ENDPOINT_PUBKEY }} \
            allowed-ips ${{ secrets.WG_ALLOWED_IPS }} \
            endpoint ${{ secrets.WG_ENDPOINT }}
          sudo ip link set mtu 1412 up dev wg0
          
      - name: Setup SSH key
        # PRIVATE_SSH_KEY :: ssh-keygen -b 4096 -C "git@github.com" -f ./id_rsa.git
        # on remote host, add id_rsa.pub to ~/.ssh/authorized_keys
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
      - name: "Copy kubernetes files to the server"
        run: |
          echo "creating directory for kube deployment"
          ssh -v ${{ secrets.SSH_USER }}@${{ secrets.ARTIFACT_HOST }} << 'ENDSSH'
            mkdir -p ~/${{ github.event.repository.name }}
          ENDSSH
          scp kubernetes/* ${{ secrets.SSH_USER }}@${{ secrets.ARTIFACT_HOST }}:~/${{ github.event.repository.name }}
      
      - name: Deploy application on server
        run: |
          ssh -v ${{ secrets.SSH_USER }}@${{ secrets.ARTIFACT_HOST }} << 'ENDSSH'
            podman kube play --replace ~/${{ github.event.repository.name}}/juniorfox-site.yaml
          ENDSSH

    deploy_gcp_app_engine:
      name: Deploy Application using gcloud actions
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: './app'
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/711506181362/locations/global/workloadIdentityPools/my-pool/providers/github-juniorfox-site'
          service_account: 'github-deployer@juniorfox-net.iam.gserviceaccount.com'
      - name: Deploy application to App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: 'juniorfox-net'
          promote: true

    sync:
        name: Sync articles database
        runs-on: ubuntu-latest
        needs: [ deploy, deploy_gcp_app_engine]
        if: needs.deploy.result == 'success' || needs.deploy_gcp_app_engine.result == 'success'
        steps:
        - name: Sync articles database via API
          run: |
            curl -X GET https://juniorfox.net/api/article/sync-database
          
